apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-cluster
  namespace: my-k8s-service
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: my-k8s-service
  project: my-k8s-service
  source:
    chart: mysql
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: latest
    helm:
      skipCrds: true
      values: |-
  syncPolicy:
    syncOptions:
      - Replace=true
    automated:
      prune: true
      selfHeal: true
