apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  template:
    spec:
      containers:
      - name: mysql
        image: bitnami/mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "test123"

