apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-k8s-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-k8s-service
  template:
    metadata:
      labels:
        app: my-k8s-service
    spec:
      containers:
      - name: my-k8s-service
        image: mtvier/my-k8s-service:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-k8s-service
  namespace: default
spec:
  selector:
    app: my-k8s-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP