apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic-stack
  namespace: default
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    chart: eck-stack
    targetRevision: 0.14.1
    helm:
      values:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true


