apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic
  namespace: default
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    chart: eck-operator
    targetRevision: HEAD
    helm:
      values:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true


