apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb-galera
  namespace: default
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: mariadb-galera
    targetRevision: 7.4.15
    helm:
      values: |
        # Aktiviert die Galera-Replikation für Hochverfügbarkeit
        galera:
          enabled: true
          replicaCount: 2  # Anzahl der Replikate für das Cluster
          clusterBootstrap: true  # Initialisiert das erste Pod als Cluster-Bootstrap
          sst: mariabackup  # Nutzt mariabackup für State Snapshot Transfer (SST)

        # Authentifizierungsdaten für MariaDB
        auth:
          rootPassword: talksgjfasg
          database: my-k8s-service
          username: myuser
          password: sdlkfj943g

        # Konfiguration für den Service
        service:
          type: ClusterIP  # Kann LoadBalancer sein, falls externer Zugriff benötigt wird
          port: 3306

        # Persistenz für dauerhafte Speicherung
        persistence:
          enabled: true
          size: "500Mi"
          storageClass: ""  # Optional: Definiere eine StorageClass, falls erforderlich

        # Galera-spezifische Konfiguration für Replikation
        galeraConfiguration:
          wsrep_cluster_name: "my-galera-cluster"
          wsrep_cluster_address: "gcomm://"
          wsrep_node_address: ""
          wsrep_sst_method: "mariabackup"
          wsrep_sst_auth: "root:test123"

        # Ressourcen-Limits für die MariaDB-Pods
        resources:
          requests:
            memory: "250Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true


