apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-k8s-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mtvier/my-k8s-service.git
    path: .
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true